create table users(user_id number(10) constraints user_id_pk primary key,username varchar2(30),constraint username_uk unique(username),first_name varchar2(30),last_name varchar2(30),email varchar2(30),constraint email_uk unique(email),password varchar2(30),mob number(10),user_tye varchar2(20),status varchar2(10));

create table resumes(resume_id number(10) constraints resume_id_pk primary key,college varchar2(50),education varchar2(30),passout_year number(10),grade varchar2(10),experiance varchar2(20),experiance_company varchar2(30),experiance_position varchar2(30),languages_spoken varchar2(50),references varchar2(50));

create table job_categories(job_category_id number(10) constraints job_category_id_pk primary key,category_name varchar2(40),constraints category_name_uk unique(category_name),category_description varchar2(500),avg_salary number(10),job_count number(10));

create table location(location_id number(10) constraints location_id_pk primary key,location_name varchar2(30),city varchar2(30),state varchar2(30),country varchar2(30),pincode number(10));

create table job_type(job_type_id number(10) constraints job_type_id_pk primary key,type_name varchar2(30),type_description varchar2(250),remote_option varchar2(20),hours_per_day number(10),type_category varchar2(30),work_schedule varchar2(30));

create table companies(company_id number(10) constraints company_id_pk primary key,company_name varchar2(30),constraints company_name_uk unique(company_name),founded_year number(10),no_of_emp number(10),website_url varchar2(50),email varchar2(50),constraints email2_uk unique(email),phone number(10),company_size varchar2(30),headquarters_location varchar2(30));

create table employers(emp_id number(10) constraints emp_id_pk primary key,user_id number(10),company_id number(10),company_size varchar2(30),company_name varchar2(30),address varchar2(100),website_url varchar2(50),industry varchar2(50),constraints user_id_fk foreign key(user_id) references users(user_id),constraints company_id_fk foreign key(company_id) references companies(company_id));

create table job_seekers(job_seeker_id number(10) constraints job_seeker_id_pk primary key,user_id number(10),resume_id number(10),location_id number(10),profile_summary varchar2(500),desired_salary number(10),availabilty varchar2(30),constraints user2_id_fk foreign key(user_id) references users(user_id),constraints resume_id_fk foreign key(resume_id) references resumes(resume_id),constraints location_id_fk foreign key(location_id) references location(location_id));

create table jobs2(job_id number(10) constraints job_id_pk2 primary key,emp_id number(10),job_tittle varchar2(50),job_description varchar2(500),job_category_id number(10),location_id number(10),job_type_id number(10),min_salary number(10),max_salary number(10),closing_date date,constraints emp_id_fk2 foreign key(emp_id) references employers(emp_id),constraints job_category_id_fk2 foreign key(job_category_id) references job_categories(job_category_id),constraints location_id_fk2 foreign key(location_id) references location(location_id),constraints job_type_id_fk2 foreign key(job_type_id) references job_type(job_type_id));

create table job_required_skills(skill_id number(10) constraints skill_id_pk primary key,skill_name varchar2(30),constraints skill_name_uk unique(skill_name),skill_description varchar2(500),proficiency_level varchar2(50),skill_category varchar2(50),job_id number(10),constraints job_id_fk foreign key(job_id) references jobs2(job_id));

create table company_offices(office_id number(10) constraints office_id_pk primary key,company_id number(10),office_location varchar2(20),city varchar2(30),state varchar2(30),country varchar2(30),contact_number number(10),email varchar2(30),manager_name varchar2(30),constraints company_id_fk2 foreign key(company_id) references companies(company_id));

create table job_seekers_skills(job_seekers_skill_id number(10) constraints job_seekers_skill_id_pk primary key,job_seeker_id number(10),skill_id number(10),proficiency_level varchar2(30),experiance varchar2(30),certification varchar2(30),related_projects varchar2(50),skill_rating number(10),resume_id number(10),constraintsjob_seeker_id_fk foreign key(job_seeker_id) references job_seekers(job_seeker_id),constraints skill_id_fk foreign key(skill_id) references job_required_skills(skill_id),constraints resume_id_fk2 foreign key(resume_id) references resumes(resume_id));

create table employer_reviews(review_id number(10) constraints review_id_pk primary key,emp_id number(10),job_seeker_id number(10),review_date date,review_text varchar2(250),rating number(10),job_position_reviewed varchar2(30),pros varchar2(100),cons varchar2(100),constraints emp_id_fk3 foreign key(emp_id) references employers(emp_id),constraints job_seeker_id_fk2 foreign key(job_seeker_id) references job_seekers(job_seeker_id));

create table messages(msg_id number(10) constraints msg_id_pk primary key,emp_id number(10),job_seeker_id number(10),subject varchar2(50),msg_body varchar2(250),send_at date,is_read varchar2(20),constraints emp_id_fk4 foreign key(emp_id) references employers(emp_id),constraints job_seeker_id_fk4 foreign key(job_seeker_id) references job_seekers(job_seeker_id));

create table certifications(certification_id number(10) constraints certification_id_pk primary key,resume_id number(10),certification_name varchar2(50),institute_name varchar2(50),start_date date,end_date date,grade varchar2(10),job_seeker_id number(10),constraints resume_id_fk7 foreign key(resume_id) references resumes(resume_id),constraints job_seeker_id_fk7 foreign key(job_seeker_id) references job_seekers(job_seeker_id));

create table applications(application_id number(10) constraints application_id_pk primary key,job_id number(10),job_seeker_id number(10),application_date date,application_status varchar2(30),resume_id number(10),constraints job_id_fk8 foreign key(job_id) references jobs2(job_id),constraints job_seeker_id_fk8 foreign key(job_seeker_id) references job_seekers(job_seeker_id),constraints resume_id_fk8 foreign key(resume_id) references resumes(resume_id));

create table interview_schedules(interview_schedule_id number(10) constraints interview_schedule_id_pk primary key,application_id number(10),emp_id number(10),interview_date date,location varchar2(50),interview_type varchar2(50),job_seeker_id number(10),interview_status varchar2(30),constraints application_id_fk9 foreign key(application_id) references applications(application_id),constraints emp_id_fk9 foreign key(emp_id) references employers(emp_id),constraints job_seeker_id_fk9 foreign key(job_seeker_id) references job_seekers(job_seeker_id));


insert all
into users values(1, 'amit123', 'Amit', 'Sharma', 'amit@email.com', 'amit@123', 9876543201, 'job_seeker', 'active')
into users values(2, 'karan456', 'Karan', 'Verma', 'karan@email.com', 'karan@456', 9876543202, 'employer', 'active')
into users values(3, 'jay789', 'Jay', 'Patel', 'jay@email.com', 'jay@789', 9876543203, 'job_seeker', 'inactive')
into users values(4, 'vijay012', 'Vijay', 'Rao', 'vijay@email.com', 'vijay@012', 9876543204, 'employer', 'active')
into users values(5, 'om345', 'Om', 'Mehta', 'om@email.com', 'om@345', 9876543205, 'job_seeker', 'active')
into users values(6, 'ravi678', 'Ravi', 'Kumar', 'ravi@email.com', 'ravi@678', 9876543206, 'employer', 'inactive')
into users values(7, 'raju901', 'Raju', 'Singh', 'raju@email.com', 'raju@901', 9876543207, 'job_seeker', 'active')
into users values(8, 'ajay234', 'Ajay', 'Gupta', 'ajay@email.com', 'ajay@234', 9876543208, 'employer', 'active')
into users values(9, 'rohit567', 'Rohit', 'Mishra', 'rohit@email.com', 'rohit@567', 9876543209, 'job_seeker', 'inactive')
into users values(10, 'anil890', 'Anil', 'Yadav', 'anil@email.com', 'anil@890', 9876543210, 'employer', 'active')
into users values(11, 'rahul321', 'Rahul', 'Joshi', 'rahul@email.com', 'rahul@321', 9876543211, 'job_seeker', 'active')
into users values(12, 'mohan654', 'Mohan', 'Desai', 'mohan@email.com', 'mohan@654', 9876543212, 'employer', 'inactive')
into users values(13, 'raj123', 'Raj', 'Singhania', 'raj@email.com', 'raj@123', 9876543213, 'job_seeker', 'active')
into users values(14, 'aman456', 'Aman', 'Khanna', 'aman@email.com', 'aman@456', 9876543214, 'employer', 'active')
into users values(15, 'arjun789', 'Arjun', 'Bajaj', 'arjun@email.com', 'arjun@789', 9876543215, 'job_seeker', 'inactive')
into users values(16, 'sanjay012', 'Sanjay', 'Sethi', 'sanjay@email.com', 'sanjay@012', 9876543216, 'employer', 'active')
into users values(17, 'vivek345', 'Vivek', 'Kapoor', 'vivek@email.com', 'vivek@345', 9876543217, 'job_seeker', 'active')
into users values(18, 'ankit678', 'Ankit', 'Chauhan', 'ankit@email.com', 'ankit@678', 9876543218, 'employer', 'inactive')
into users values(19, 'deepak901', 'Deepak', 'Nair', 'deepak@email.com', 'deepak@901', 9876543219, 'job_seeker', 'active')
into users values(20, 'sumit234', 'Sumit', 'Roy', 'sumit@email.com', 'sumit@234', 9876543220, 'employer', 'active')
into users values(21, 'manoj567', 'Manoj', 'Thakur', 'manoj@email.com', 'manoj@567', 9876543221, 'job_seeker', 'inactive')
into users values(22, 'sunil890', 'Sunil', 'Das', 'sunil@email.com', 'sunil@890', 9876543222, 'employer', 'active')
into users values(23, 'vikas321', 'Vikas', 'Agrawal', 'vikas@email.com', 'vikas@321', 9876543223, 'job_seeker', 'active')
into users values(24, 'ramesh654', 'Ramesh', 'Pandey', 'ramesh@email.com', 'ramesh@654', 9876543224, 'employer', 'inactive')
into users values(25, 'shyam123', 'Shyam', 'Malhotra', 'shyam@email.com', 'shyam@123', 9876543225, 'job_seeker', 'active')
into users values(26, 'pranav456', 'Pranav', 'Tiwari', 'pranav@email.com', 'pranav@456', 9876543226, 'employer', 'active')
into users values(27, 'nilesh789', 'Nilesh', 'Bhatia', 'nilesh@email.com', 'nilesh@789', 9876543227, 'job_seeker', 'inactive')
into users values(28, 'ganesh012', 'Ganesh', 'Naik', 'ganesh@email.com', 'ganesh@012', 9876543228, 'employer', 'active')
into users values(29, 'ashok345', 'Ashok', 'Reddy', 'ashok@email.com', 'ashok@345', 9876543229, 'job_seeker', 'active')
into users values(30, 'suresh678', 'Suresh', 'Shetty', 'suresh@email.com', 'suresh@678', 9876543230, 'employer', 'inactive')
into users values(31, 'lokesh901', 'Lokesh', 'Kohli', 'lokesh@email.com', 'lokesh@901', 9876543231, 'job_seeker', 'active')
into users values(32, 'manish234', 'Manish', 'Dutta', 'manish@email.com', 'manish@234', 9876543232, 'employer', 'active')
into users values(33, 'abhay567', 'Abhay', 'Sen', 'abhay@email.com', 'abhay@567', 9876543233, 'job_seeker', 'inactive')
into users values(34, 'atul890', 'Atul', 'Mitra', 'atul@email.com', 'atul@890', 9876543234, 'employer', 'active')
into users values(35, 'tarun321', 'Tarun', 'Rai', 'tarun@email.com', 'tarun@321', 9876543235, 'job_seeker', 'active')
into users values(36, 'dinesh654', 'Dinesh', 'Saxena', 'dinesh@email.com', 'dinesh@654', 9876543236, 'employer', 'inactive')
into users values(37, 'ajit123', 'Ajit', 'Puri', 'ajit@email.com', 'ajit@123', 9876543237, 'job_seeker', 'active')
into users values(38, 'gopal456', 'Gopal', 'Chandra', 'gopal@email.com', 'gopal@456', 9876543238, 'employer', 'active')
into users values(39, 'naveen789', 'Naveen', 'Dewan', 'naveen@email.com', 'naveen@789', 9876543239, 'job_seeker', 'inactive')
into users values(40, 'lalit012', 'Lalit', 'Tripathi', 'lalit@email.com', 'lalit@012', 9876543240, 'employer', 'active')
into users values(41, 'vinay345', 'Vinay', 'Awasthi', 'vinay@email.com', 'vinay@345', 9876543241, 'job_seeker', 'active')
into users values(42, 'siddharth678', 'Siddharth', 'Nair', 'siddharth@email.com', 'siddharth@678', 9876543242, 'employer', 'inactive')
into users values(43, 'neha901', 'Neha', 'Gupta', 'neha@email.com', 'neha@901', 9876543243, 'job_seeker', 'active')
into users values(44, 'priya234', 'Priya', 'Mehta', 'priya@email.com', 'priya@234', 9876543244, 'employer', 'active')
into users values(45, 'rahul456', 'Rahul', 'Bansal', 'rahul2@email.com', 'rahul@456', 9876543245, 'job_seeker', 'inactive')
into users values(46, 'kavita789', 'Kavita', 'Sharma', 'kavita@email.com', 'kavita@789', 9876543246, 'employer', 'active')
into users values(47, 'gita012', 'Gita', 'Bhatia', 'gita@email.com', 'gita@012', 9876543247, 'job_seeker', 'active')
into users values(48, 'shweta345', 'Shweta', 'Choudhary', 'shweta@email.com', 'shweta@345', 9876543248, 'employer', 'inactive')
into users values(49, 'komal678', 'Komal', 'Singh', 'komal@email.com', 'komal@678', 9876543249, 'job_seeker', 'active')
into users values(50, 'rahul789', 'Rahul', 'Yadav', 'rahul3@email.com', 'rahul@789', 9876543250, 'employer', 'active')
into users values(51, 'deepika012', 'Deepika', 'Kumar', 'deepika@email.com', 'deepika@012', 9876543251, 'job_seeker', 'inactive')
into users values(52, 'neeraj345', 'Neeraj', 'Soni', 'neeraj@email.com', 'neeraj@345', 9876543252, 'employer', 'active')
into users values(53, 'shivani678', 'Shivani', 'Sharma', 'shivani@email.com', 'shivani@678', 9876543253, 'job_seeker', 'active')
into users values(54, 'kiran901', 'Kiran', 'Pillai', 'kiran@email.com', 'kiran@901', 9876543254, 'employer', 'inactive')
into users values(55, 'manju234', 'Manju', 'Deshmukh', 'manju@email.com', 'manju@234', 9876543255, 'job_seeker', 'active')
into users values(56, 'reema456', 'Reema', 'Agarwal', 'reema@email.com', 'reema@456', 9876543256, 'employer', 'active')
into users values(57, 'pankaj789', 'Pankaj', 'Jha', 'pankaj@email.com', 'pankaj@789', 9876543257, 'job_seeker', 'inactive')
into users values(58, 'girish012', 'Girish', 'Bansal', 'girish@email.com', 'girish@012', 9876543258, 'employer', 'active')
into users values(59, 'suresh345', 'Suresh', 'Choudhary', 'suresh2@email.com', 'suresh@345', 9876543259, 'job_seeker', 'active')
into users values(60, 'anuj678', 'Anuj', 'Patel', 'anuj@email.com', 'anuj@678', 9876543260, 'employer', 'inactive')
into users values(61, 'aakash901', 'Aakash', 'Yadav', 'aakash@email.com', 'aakash@901', 9876543261, 'job_seeker', 'active')
into users values(62, 'pranav234', 'Pranav', 'Gupta', 'pranav2@email.com', 'pranav@234', 9876543262, 'employer', 'active')
into users values(63, 'rakesh456', 'Rakesh', 'Dutta', 'rakesh@email.com', 'rakesh@456', 9876543263, 'job_seeker', 'inactive')
into users values(64, 'vinod789', 'Vinod', 'Rai', 'vinod@email.com', 'vinod@789', 9876543264, 'employer', 'active')
into users values(65, 'pooja012', 'Pooja', 'Verma', 'pooja@email.com', 'pooja@012', 9876543265, 'job_seeker', 'active')
into users values(66, 'preeti345', 'Preeti', 'Agrawal', 'preeti@email.com', 'preeti@345', 9876543266, 'employer', 'inactive')
into users values(67, 'sanjana678', 'Sanjana', 'Sharma', 'sanjana@email.com', 'sanjana@678', 9876543267, 'job_seeker', 'active')
into users values(68, 'rajesh901', 'Rajesh', 'Bhatia', 'rajesh@email.com', 'rajesh@901', 9876543268, 'employer', 'active')
into users values(69, 'bala234', 'Bala', 'Nair', 'bala@email.com', 'bala@234', 9876543269, 'job_seeker', 'inactive')
into users values(70, 'tanu678', 'Tanu', 'Desai', 'tanu@email.com', 'tanu@678', 9876543270, 'employer', 'active')
select * from dual;


insert all
into resumes values(101, 'Savitribai Phule University', 'B.Tech', 2020, 'A', '2 year', 'Tech Solutions', 'Software Engineer', 'English, Hindi', NULL)
into resumes values(102, 'Shivaji University kolhapur', 'M.Sc', 2019, 'B', '1 year', 'DataCorp', 'Data Analyst', 'English', 'Mr. Sharma')
into resumes values(103, 'Symbiosis International University', 'MBA', 2022, 'A+', NULL, NULL, NULL, 'English, French', NULL)
into resumes values(104, 'Bharati Vidyapeeth Deemed University', 'B.Com', 2023, 'B+', '1.5 year', 'Finance Inc', 'Accountant', 'English, Spanish', 'Mr. Sharma')
into resumes values(105, 'Vishwakarma Institute of Technology', 'B.Sc', 2022, 'A', NULL, NULL, NULL, 'English', NULL)
into resumes values(106, 'D.Y. Patil College of Engineering', 'B.Tech', 2024, 'A+', '3 year', 'Tech Innovations', 'Full Stack Developer', 'English, Hindi', 'Ms. Verma')
into resumes values(107, 'Fergusson College', 'Ph.D', 2020, 'A+', NULL, NULL, NULL, 'English, Mandarin', NULL)
into resumes values(108, 'Wadia College', 'MCA', 2022, 'B', '2 year', 'Web Solutions', 'Web Developer', 'English', NULL)
into resumes values(109, 'Sinhgad Institute of Technology and Science', 'MCA', 2018, 'B', NULL, NULL, NULL, 'English, German', 'Ms. Verma')
into resumes values(110, 'Dr. D.Y. Patil Vidyapeeth', 'M.Tech', 2018, 'A', NULL, NULL, NULL, 'English', NULL)
into resumes values(111, 'Indira Gandhi Institute', 'BCA', 2019, 'A+', '4 year', 'Data Solutions', 'Data Scientist', 'English, Hindi', NULL)
into resumes values(112, 'B.K. Birla College', 'M.Sc', 2021, 'B', NULL, NULL, NULL, 'English', 'Mr. Rao')
into resumes values(113, 'Institute of Business Management', 'MBA', 2020, 'A', '2 year', 'Business Inc.', 'Business Analyst', 'English, Spanish', NULL)
into resumes values(114, 'Wadia College','B.Com', 2018, 'C+', NULL, NULL, NULL, 'English, French', 'Ms. Patel')
into resumes values(115, 'Shivaji University Pune', 'MCA', 2022, 'B+', '1 year', 'IT Solutions', 'Junior Developer', 'English', NULL)
into resumes values(116, 'Maharashtra Institute of Technology ', 'B.Tech', 2024, 'A', NULL, NULL, NULL, 'English', 'Mr. Gupta')
into resumes values(117, 'Saraswati College of Engineering', 'MCA', 2021, 'A+', '3 year', 'App Development', 'Mobile Developer', 'English, Hindi', NULL)
into resumes values(118, 'Sanjivani College of Engineering', 'MBA', 2020, 'B+', NULL, NULL, NULL, 'English, Mandarin', 'Ms. Joshi')
into resumes values(119, 'AISSMS College of Engineering', 'B.Tech', 2023, 'A', '2 year', 'CyberTech', 'Security Analyst', 'English', NULL)
into resumes values(120, 'Pune School of Business Management', 'MBA', 2021, 'A+', NULL, NULL, NULL, 'English, German', 'Mr. Mehta')
into resumes values(121, 'University of Mumbai', 'M.Tech', 2018, 'B+', '5 year', 'Retail Co.', 'Operations Manager', 'English', NULL)
into resumes values(122, 'IIT', 'MCA', 2020, 'A', '1 year', 'Marketing Firm', 'Marketing Executive', 'English', NULL)
into resumes values(123, 'Veermata Jijabai Technological Institute', 'MCA', 2021, 'B+', NULL, NULL, NULL, 'English', 'Mr. Mehta')
into resumes values(124, 'Sardar Patel Institute', 'M.Sc', 2020, 'A', '4 years', 'HealthTech', 'Quality Analyst', 'English, Hindi', NULL)
into resumes values(125, 'Rajiv Gandhi Institute', 'MCA', 2022, 'B+', NULL, NULL, NULL, 'English', NULL)
into resumes values(126, 'Smt. Indira Gandhi College', 'M.Tech', 2021, 'A', '3 year', 'Tech Innovations', 'DevOps Engineer', 'English, Spanish', 'Mr. Naik')
into resumes values(127, 'Government College of Engineering, Karad', 'MCA', 2020, 'A', NULL, NULL, NULL, 'English, Hindi', NULL)
into resumes values(128, 'Y.C. college of Science karad', 'BBA', 2019, 'B', '2 year', 'Retail Group', 'Sales Executive', 'English', NULL)
into resumes values(129, 'SGM college karad', 'B.Com', 2022, 'C+', NULL, NULL, NULL, 'English, Hindi', 'Mr. Kapoor')
into resumes values(130, 'Savitribai Phule University', 'B.Tech', 2021, 'A+', '1 year', 'E-commerce Co.', 'Product Manager', 'English', NULL)
into resumes values(131, 'Pune School of Business Management', 'MBA', 2020, 'A', NULL, NULL, NULL, 'English, Mandarin', 'Ms. Desai')
into resumes values(132, 'IIT', 'B.Tech', 2019, 'B', '2 years', 'Logistics Co.', 'Logistics Manager', 'English', NULL)
into resumes values(133, 'Wadia College', 'BBA', 2021, 'A+', NULL, NULL, NULL, 'English', NULL)
into resumes values(134, 'Shivaji University Pune', 'MBA', 2020, 'B+', '3 year', 'Consulting Inc.', 'Consultant', 'English, Spanish', 'Mr. Singh')
into resumes values(135, 'Dr. D.Y. Patil Vidyapeeth', 'Ph.D', 2021, 'A', NULL, NULL, NULL, 'English', NULL)
into resumes values(136, 'Symbiosis International University', 'B.Sc', 2019, 'C', '2 years', 'Finance Group', 'Financial Analyst', 'English, Hindi', NULL)
into resumes values(137, 'Government College of Engineering, Karad', 'M.Tech', 2022, 'B+', '1 year', 'Engineering Co.', 'Research Assistant', 'English', 'Mr. Singh')
into resumes values(138, 'AISSMS College of Engineering', 'BCA', 2020, 'A', NULL, NULL, NULL, 'English', NULL)
into resumes values(139, 'Fergusson College', 'MBA', 2023, 'B', '4 years', 'Real Estate', 'Agent', 'English, Mandarin', NULL)
into resumes values(140, 'Fergusson College', 'M.Com', 2024, 'A', NULL, NULL, NULL, 'English', 'Mr. Desai')
into resumes values(141, 'MIT School of Business', 'MBA', 2021, 'A+', '2 year', 'Finance Corp', 'Financial Manager', 'English, Hindi', NULL)
into resumes values(142, 'Institute of Technology', 'B.Tech', 2020, 'B+', NULL, NULL, NULL, 'English', 'Mr. Patil')
into resumes values(143, 'Birla Institute of Technology', 'M.Sc', 2019, 'A', '1 year', 'Analytics Co.', 'Data Scientist', 'English, Spanish', NULL)
into resumes values(144, 'Nirma University', 'B.Com', 2023, 'A', NULL, NULL, NULL, 'English', NULL)
into resumes values(145, 'LNM Institute of Technology', 'B.Tech', 2022, 'A+', '3 year', 'Tech Innovators', 'Software Developer', 'English', 'Ms. Iyer')
into resumes values(146, 'SRM University', 'MCA', 2021, 'B', '2 year', 'App Solutions', 'App Developer', 'English', NULL)
into resumes values(147, 'Manipal University', 'Ph.D', 2020, 'A+', NULL, NULL, NULL, 'English, French', 'Dr. Rao')
into resumes values(148, 'Bharati Vidyapeeth University', 'M.Sc', 2018, 'C', '1 year', 'Health Solutions', 'Health Analyst', 'English', NULL)
into resumes values(149, 'PES University', 'B.Tech', 2023, 'B+', '1 year', 'Cyber Security', 'Security Consultant', 'English, Hindi', 'Mr. Singh')
into resumes values(150, 'Dhirubhai Ambani Institute', 'MBA', 2021, 'A+', NULL, NULL, NULL, 'English, Mandarin', NULL)
into resumes values(151, 'Jadavpur University', 'M.Tech', 2019, 'A', '2 year', 'Engineering Corp', 'Project Manager', 'English', 'Mr. Gupta')
into resumes values(152, 'Delhi University', 'BCA', 2022, 'B+', NULL, NULL, NULL, 'English', 'Ms. Sharma')
into resumes values(153, 'Jamia Millia Islamia', 'MBA', 2020, 'B', NULL, NULL, NULL, 'English, Spanish', NULL)
into resumes values(154, 'Osmania University', 'BBA', 2019, 'A', '3 year', 'Marketing Firm', 'Marketing Manager', 'English', 'Mr. Kapoor')
into resumes values(155, 'Loyola College', 'M.Com', 2021, 'A+', '2 year', 'Finance House', 'Account Manager', 'English', NULL)
into resumes values(156, 'NIT Surat', 'B.Tech', 2023, 'A', NULL, NULL, NULL, 'English, Hindi', 'Mr. Iyer')
into resumes values(157, 'SASTRA University', 'M.Tech', 2020, 'B+', '1 year', 'Tech Solutions', 'DevOps Engineer', 'English', NULL)
into resumes values(158, 'UPES', 'M.Sc', 2021, 'A', '2 year', 'Energy Co.', 'Quality Engineer', 'English', 'Mr. Sharma')
into resumes values(159, 'GGSIPU', 'MBA', 2023, 'A+', '3 year', 'Consulting Group', 'Consultant', 'English, French', NULL)
into resumes values(160, 'Rajasthan Technical University', 'B.Com', 2022, 'C', '1 year', 'Retail Corp', 'Store Manager', 'English', NULL)
into resumes values(161, 'Thapar University', 'MCA', 2020, 'A+', NULL, NULL, NULL, 'English', 'Ms. Joshi')
into resumes values(162, 'Punjab University', 'B.Tech', 2019, 'B+', '2 year', 'Software Inc', 'Software Tester', 'English', NULL)
into resumes values(163, 'BHU', 'M.Sc', 2021, 'B', NULL, NULL, NULL, 'English, Hindi', 'Mr. Mehta')
into resumes values(164, 'Aligarh Muslim University', 'MBA', 2020, 'A', '3 year', 'Finance Services', 'Financial Analyst', 'English', NULL)
into resumes values(165, 'Lovely Professional University', 'BCA', 2022, 'B+', NULL, NULL, NULL, 'English', 'Mr. Desai')
into resumes values(166, 'University of Pune', 'M.Com', 2019, 'A+', '4 year', 'Finance Group', 'Tax Consultant', 'English', 'Ms. Patel')
into resumes values(167, 'GITAM University', 'BBA', 2023, 'B', NULL, NULL, NULL, 'English', NULL)
into resumes values(168, 'SVNIT', 'B.Tech', 2020, 'C+', '2 year', 'Tech Solutions', 'Technical Support', 'English', NULL)
into resumes values(169, 'DIT University', 'M.Tech', 2021, 'A+', NULL, NULL, NULL, 'English, Hindi', 'Mr. Gupta')
into resumes values(170, 'Shivaji University', 'M.Sc', 2020, 'B+', NULL, NULL, NULL, 'English', NULL)
select * from dual;


insert all
into job_categories values(201, 'Information Technology', 'Roles related to IT and software development', 800000, 1200)
into job_categories values(202, 'Engineering', 'Various engineering disciplines including civil, mechanical, and electrical', 700000, 800)
into job_categories values(203, 'Healthcare', 'Jobs in hospitals, clinics, and healthcare facilities', 600000, 500)
into job_categories values(204, 'Finance', 'Financial services including banking, accounting, and investment', 900000, 400)
into job_categories values(205, 'Marketing', 'Roles focused on promoting products and services', 650000, 600)
into job_categories values(206, 'Education', 'Jobs in teaching and educational administration', 500000, 300)
into job_categories values(207, 'Human Resources', 'Roles related to employee recruitment and management', 550000, 200)
into job_categories values(208, 'Sales', 'Jobs focused on selling products and services', 600000, 700)
into job_categories values(209, 'Manufacturing', 'Roles in production and manufacturing processes', 550000, 450)
into job_categories values(210, 'Customer Service', 'Roles focused on assisting customers and resolving issues', 400000, 300)
into job_categories values(211, 'Real Estate', 'Roles in property management and sales', 600000, 250)
into job_categories values(212, 'Retail', 'Jobs in the retail industry, including store management and sales', 450000, 400)
into job_categories values(213, 'Construction', 'Roles in building and infrastructure development', 550000, 300)
into job_categories values(214, 'Transportation', 'Roles related to transport services and logistics', 480000, 200)
into job_categories values(215, 'Research and Development', 'Jobs focused on innovation and product development', 900000, 150)
into job_categories values(216, 'Data Science', 'Roles in data analysis and interpretation', 950000, 250)
into job_categories values(217, 'Legal', 'Jobs in law and legal services', 850000, 300)
into job_categories values(218, 'Hospitality', 'Jobs in hotels, restaurants, and tourism', 600000, 400)
into job_categories values(219, 'Pharmaceuticals', 'Roles in drug development and sales', 700000, 200)
into job_categories values(220, 'Telecommunications', 'Jobs in communication technology', 750000, 350)
into job_categories values(221, 'Media and Journalism', 'Roles in news, broadcasting, and publishing', 550000, 300)
into job_categories values(222, 'Arts and Entertainment', 'Jobs in creative fields like music and film', 650000, 250)
into job_categories values(223, 'Aerospace', 'Roles in aviation and space exploration', 800000, 200)
into job_categories values(224, 'Insurance', 'Jobs in underwriting, claims, and sales', 600000, 150)
into job_categories values(225, 'Fashion', 'Roles in design, merchandising, and retail', 500000, 300)
into job_categories values(226, 'Agriculture', 'Jobs in farming and agribusiness', 400000, 200)
into job_categories values(227, 'Government', 'Roles in public service and administration', 550000, 350)
into job_categories values(228, 'Non-Profit', 'Jobs in charitable organizations', 500000, 300)
into job_categories values(229, 'Cybersecurity', 'Roles focused on protecting information systems', 950000, 100)
into job_categories values(230, 'Blockchain', 'Jobs in cryptocurrency and blockchain technology', 900000, 150)
into job_categories values(231, 'Environmental Science', 'Roles in conservation and sustainability', 600000, 200)
into job_categories values(232, 'Supply Chain Management', 'Jobs in logistics and supply chain operations', 700000, 250)
into job_categories values(233, 'Quality Assurance', 'Roles focused on maintaining product standards', 500000, 300)
into job_categories values(234, 'Public Relations', 'Jobs in managing public perception and communications', 650000, 200)
into job_categories values(235, 'Event Management', 'Roles in organizing events and conferences', 450000, 300)
into job_categories values(236, 'Social Media Management', 'Jobs in online community engagement and marketing', 500000, 400)
into job_categories values(237, 'Graphic Design', 'Roles in visual communication and design', 550000, 300)
into job_categories values(238, 'Database Administration', 'Jobs in data management and database systems', 700000, 250)
into job_categories values(239, 'Network Administration', 'Roles in managing computer networks', 800000, 200)
into job_categories values(240, 'Clinical Research', 'Jobs in medical and clinical studies', 600000, 150)
into job_categories values(241, 'IT Support', 'Roles in technical assistance and troubleshooting', 450000, 300)
into job_categories values(242, 'Product Management', 'Jobs in product development and strategy', 750000, 300)
into job_categories values(243, 'Business Analysis', 'Roles focused on analyzing business processes and solutions', 600000, 200)
into job_categories values(244, 'UX/UI Design', 'Jobs in user experience and interface design', 650000, 250)
into job_categories values(245, 'Training and Development', 'Roles in employee training and education', 500000, 200)
into job_categories values(246, 'Technical Writing', 'Jobs in creating manuals and documentation', 550000, 300)
into job_categories values(247, 'Foreign Language Instruction', 'Roles in teaching foreign languages', 450000, 200)
into job_categories values(248, 'Fitness and Wellness', 'Jobs in health and fitness coaching', 400000, 300)
into job_categories values(249, 'Digital Marketing', 'Roles in online advertising and SEO', 600000, 250)
into job_categories values(250, 'Investment Banking', 'Jobs in financial advising and investment services', 950000, 150)
into job_categories values(251, 'E-commerce', 'Roles in online retail and sales', 500000, 300)
into job_categories values(252, 'Food Services', 'Jobs in food preparation and services', 400000, 400)
into job_categories values(253, 'Pet Services', 'Roles in pet care and grooming', 350000, 200)
into job_categories values(254, 'Home Services', 'Jobs in home maintenance and repair', 450000, 300)
into job_categories values(255, 'Virtual Assistance', 'Roles in remote administrative support', 300000, 150)
into job_categories values(256, 'Insurance Adjusting', 'Jobs in assessing insurance claims', 500000, 200)
into job_categories values(257, 'Solar Energy', 'Roles in renewable energy and solar power', 700000, 150)
into job_categories values(258, 'Artificial Intelligence', 'Jobs in AI development and research', 800000, 100)
into job_categories values(259, 'Home Health Care', 'Roles in at-home medical assistance', 600000, 200)
into job_categories values(260, 'Childcare', 'Jobs in child care and education', 400000, 300)
into job_categories values(261, 'Content Creation', 'Roles in producing digital content', 500000, 250)
into job_categories values(262, 'Freelancing', 'Jobs in various freelance roles', 400000, 200)
into job_categories values(263, 'Telemarketing', 'Roles in outbound sales calls', 350000, 300)
into job_categories values(264, 'SEO Consulting', 'Jobs in search engine optimization strategies', 550000, 200)
into job_categories values(265, 'Financial Planning', 'Roles in personal finance and investment advice', 700000, 250)
into job_categories values(266, 'Corporate Training', 'Jobs in business skills training', 600000, 300)
into job_categories values(267, 'Home Inspection', 'Roles in assessing property conditions', 500000, 200)
into job_categories values(268, 'Art Therapy', 'Jobs in therapeutic art practices', 400000, 250)
into job_categories values(269, 'Debt Counseling', 'Roles in financial advice and debt management', 350000, 150)
into job_categories values(270, 'Nutrition', 'Jobs in dietary consulting and meal planning', 400000, 300)
select * from dual;


insert all
into location values(301, 'Kharadi', 'Pune', 'Maharashtra', 'India', 411014)
into location values(302, 'Shivajinagar', 'Pune', 'Maharashtra', 'India', 411005)
into location values(303, 'Andheri', 'Mumbai', 'Maharashtra', 'India', 400053)
into location values(304, 'Dadar', 'Mumbai', 'Maharashtra', 'India', 400014)
into location values(305, 'Nashik Road', 'Nashik', 'Maharashtra', 'India', 422101)
into location values(306, 'Panchavati', 'Nashik', 'Maharashtra', 'India', 422003)
into location values(307, 'Shivaji University', 'Kolhapur', 'Maharashtra', 'India', 416004)
into location values(308, 'Rajaram College', 'Kolhapur', 'Maharashtra', 'India', 416008)
into location values(309, 'Cidco', 'Aurangabad', 'Maharashtra', 'India', 431003)
into location values(310, 'Garkheda', 'Aurangabad', 'Maharashtra', 'India', 431009)
into location values(311, 'Thane West', 'Thane', 'Maharashtra', 'India', 400601)
into location values(312, 'Kalyan', 'Thane', 'Maharashtra', 'India', 421301)
into location values(313, 'Solapur City', 'Solapur', 'Maharashtra', 'India', 413001)
into location values(314, 'Shivaji Nagar', 'Solapur', 'Maharashtra', 'India', 413004)
into location values(315, 'Satara', 'Satara', 'Maharashtra', 'India', 415001)
into location values(316, 'Karad', 'Satara', 'Maharashtra', 'India', 415110)
into location values(317, 'Nagpur City', 'Nagpur', 'Maharashtra', 'India', 440001)
into location values(318, 'Pardi', 'Nagpur', 'Maharashtra', 'India', 440025)
into location values(319, 'Baner', 'Pune', 'Maharashtra', 'India', 411045)
into location values(320, 'Wadala', 'Mumbai', 'Maharashtra', 'India', 400031)
into location values(321, 'Trimbak', 'Nashik', 'Maharashtra', 'India', 422212)
into location values(322, 'Mahatma Phule Road', 'Kolhapur', 'Maharashtra', 'India', 416012)
into location values(323, 'Kranti Nagar', 'Aurangabad', 'Maharashtra', 'India', 431001)
into location values(324, 'Shahpura', 'Thane', 'Maharashtra', 'India', 400607)
into location values(325, 'Mangalwedha', 'Solapur', 'Maharashtra', 'India', 413305)
into location values(326, 'Sangli', 'Satara', 'Maharashtra', 'India', 416416)
into location values(327, 'Umred', 'Nagpur', 'Maharashtra', 'India', 441203)
into location values(328, 'Aundh', 'Pune', 'Maharashtra', 'India', 411007)
into location values(329, 'Vikhroli', 'Mumbai', 'Maharashtra', 'India', 400083)
into location values(330, 'Nashik Pune Road', 'Nashik', 'Maharashtra', 'India', 422103)
into location values(331, 'Shivaji Chowk', 'Kolhapur', 'Maharashtra', 'India', 416004)
into location values(332, 'Kranti Nagar', 'Aurangabad', 'Maharashtra', 'India', 431210)
into location values(333, 'Bhiwandi', 'Thane', 'Maharashtra', 'India', 421302)
into location values(334, 'Solapur Road', 'Solapur', 'Maharashtra', 'India', 413223)
into location values(335, 'Khandala', 'Satara', 'Maharashtra', 'India', 415001)
into location values(336, 'Sadar', 'Nagpur', 'Maharashtra', 'India', 440001)
into location values(337, 'Hadapsar', 'Pune', 'Maharashtra', 'India', 411028)
into location values(338, 'Ghatkopar', 'Mumbai', 'Maharashtra', 'India', 400077)
into location values(339, 'Nashik Highway', 'Nashik', 'Maharashtra', 'India', 422001)
into location values(340, 'Mahalaxmi', 'Kolhapur', 'Maharashtra', 'India', 416001)
into location values(341, 'Bhiwandi', 'Thane', 'Maharashtra', 'India', 421302)
into location values(342, 'Bhiwandi', 'Thane', 'Maharashtra', 'India', 421302)
into location values(343, 'Kalyan', 'Thane', 'Maharashtra', 'India', 421301)
into location values(344, 'Kalyan', 'Thane', 'Maharashtra', 'India', 421301)
into location values(345, 'Shivajinagar', 'Pune', 'Maharashtra', 'India', 411005)
into location values(346, 'Shivajinagar', 'Pune', 'Maharashtra', 'India', 411005)
into location values(347, 'Thane West', 'Thane', 'Maharashtra', 'India', 400601)
into location values(348, 'Thane West', 'Thane', 'Maharashtra', 'India', 400601)
into location values(349, 'Aundh', 'Pune', 'Maharashtra', 'India', 411007)
into location values(350, 'Aundh', 'Pune', 'Maharashtra', 'India', 411007)
into location values(351, 'Indiranagar', 'Bengaluru', 'Karnataka', 'India', 560038)
into location values(352, 'Jayanagar', 'Bengaluru', 'Karnataka', 'India', 560011)
into location values(353, 'Kalyan Nagar', 'Bengaluru', 'Karnataka', 'India', 560043)
into location values(354, 'Vijayanagar', 'Bengaluru', 'Karnataka', 'India', 560040)
into location values(355, 'Gokulam', 'Mysuru', 'Karnataka', 'India', 570002)
into location values(356, 'Kankanady', 'Mangaluru', 'Karnataka', 'India', 575002)
into location values(357, 'T Nagar', 'Chennai', 'Tamil Nadu', 'India', 600017)
into location values(358, 'Anna Nagar', 'Chennai', 'Tamil Nadu', 'India', 600040)
into location values(359, 'Kota', 'Mysuru', 'Karnataka', 'India', 570004)
into location values(360, 'Hitech City', 'Hyderabad', 'Telangana', 'India', 500081)
into location values(361, 'Banjara Hills', 'Hyderabad', 'Telangana', 'India', 500034)
into location values(362, 'Dwaraka Nagar', 'Visakhapatnam', 'Andhra Pradesh', 'India', 530016)
into location values(363, 'Rajendra Nagar', 'Vijayawada', 'Andhra Pradesh', 'India', 520002)
into location values(364, 'Bhadbhada', 'Bhopal', 'Madhya Pradesh', 'India', 462030)
into location values(365, 'Rajendra Nagar', 'Indore', 'Madhya Pradesh', 'India', 452012)
into location values(366, 'Hazratganj', 'Lucknow', 'Uttar Pradesh', 'India', 226001)
into location values(367, 'Kalyanpur', 'Kanpur', 'Uttar Pradesh', 'India', 208017)
into location values(368, 'C-Scheme', 'Jaipur', 'Rajasthan', 'India', 302001)
into location values(369, 'Udaipur City', 'Udaipur', 'Rajasthan', 'India', 313001)
into location values(370, 'Boring Road', 'Patna', 'Bihar', 'India', 800001)
select * from dual;


insert all
into job_type values(401, 'Full-time', 'Standard full-time employment', 'No', 8, 'Permanent', 'Day')
into job_type values(402, 'Full-time', 'Standard full-time employment', 'No', 8, 'Permanent', 'Night')
into job_type values(403, 'Full-time', 'Standard full-time employment', 'No', 8, 'Permanent', 'Rotating')
into job_type values(404, 'Full-time', 'Standard full-time employment', 'No', 8, 'Permanent', 'Flexible')
into job_type values(405, 'Part-time', 'Part-time employment with flexible hours', 'Yes', 4, 'Temporary', 'Day')
into job_type values(406, 'Part-time', 'Part-time employment with flexible hours', 'Yes', 4, 'Temporary', 'Night')
into job_type values(407, 'Part-time', 'Part-time employment with flexible hours', 'Yes', 4, 'Temporary', 'Rotating')
into job_type values(408, 'Part-time', 'Part-time employment with flexible hours', 'Yes', 4, 'Temporary', 'Flexible')
into job_type values(409, 'Internship', 'Temporary position for students', 'Yes', 6, 'Internship', 'Day')
into job_type values(410, 'Internship', 'Temporary position for students', 'Yes', 6, 'Internship', 'Night')
into job_type values(411, 'Internship', 'Temporary position for students', 'Yes', 6, 'Internship', 'Rotating')
into job_type values(412, 'Internship', 'Temporary position for students', 'Yes', 6, 'Internship', 'Flexible')
into job_type values(413, 'Full-time', 'Full-time employment with benefits', 'No', 8, 'Permanent', 'Day')
into job_type values(414, 'Full-time', 'Full-time employment with benefits', 'No', 8, 'Permanent', 'Night')
into job_type values(415, 'Full-time', 'Full-time employment with benefits', 'No', 8, 'Permanent', 'Rotating')
into job_type values(416, 'Full-time', 'Full-time employment with benefits', 'No', 8, 'Permanent', 'Flexible')
into job_type values(417, 'Part-time', 'Part-time work with flexible hours', 'Yes', 4, 'Temporary', 'Day')
into job_type values(418, 'Part-time', 'Part-time work with flexible hours', 'Yes', 4, 'Temporary', 'Night')
into job_type values(419, 'Part-time', 'Part-time work with flexible hours', 'Yes', 4, 'Temporary', 'Rotating')
into job_type values(420, 'Part-time', 'Part-time work with flexible hours', 'Yes', 4, 'Temporary', 'Flexible')
into job_type values(421, 'Internship', 'Internship opportunity for college students', 'Yes', 6, 'Internship', 'Day')
into job_type values(422, 'Internship', 'Internship opportunity for college students', 'Yes', 6, 'Internship', 'Night')
into job_type values(423, 'Internship', 'Internship opportunity for college students', 'Yes', 6, 'Internship', 'Rotating')
into job_type values(424, 'Internship', 'Internship opportunity for college students', 'Yes', 6, 'Internship', 'Flexible')
into job_type values(425, 'Full-time', 'Full-time role with a stable schedule', 'No', 8, 'Permanent', 'Day')
into job_type values(426, 'Full-time', 'Full-time role with a stable schedule', 'No', 8, 'Permanent', 'Night')
into job_type values(427, 'Full-time', 'Full-time role with a stable schedule', 'No', 8, 'Permanent', 'Rotating')
into job_type values(428, 'Full-time', 'Full-time role with a stable schedule', 'No', 8, 'Permanent', 'Flexible')
into job_type values(429, 'Part-time', 'Flexible part-time work', 'Yes', 4, 'Temporary', 'Day')
into job_type values(430, 'Part-time', 'Flexible part-time work', 'Yes', 4, 'Temporary', 'Night')
into job_type values(431, 'Part-time', 'Flexible part-time work', 'Yes', 4, 'Temporary', 'Rotating')
into job_type values(432, 'Part-time', 'Flexible part-time work', 'Yes', 4, 'Temporary', 'Flexible')
into job_type values(433, 'Internship', 'Internship for skill development', 'Yes', 6, 'Internship', 'Day')
into job_type values(434, 'Internship', 'Internship for skill development', 'Yes', 6, 'Internship', 'Night')
into job_type values(435, 'Internship', 'Internship for skill development', 'Yes', 6, 'Internship', 'Rotating')
into job_type values(436, 'Internship', 'Internship for skill development', 'Yes', 6, 'Internship', 'Flexible')
into job_type values(437, 'Full-time', 'Standard full-time position', 'No', 8, 'Permanent', 'Day')
into job_type values(438, 'Full-time', 'Standard full-time position', 'No', 8, 'Permanent', 'Night')
into job_type values(439, 'Full-time', 'Standard full-time position', 'No', 8, 'Permanent', 'Rotating')
into job_type values(440, 'Full-time', 'Standard full-time position', 'No', 8, 'Permanent', 'Flexible')
into job_type values(441, 'Part-time', 'Part-time role for students', 'Yes', 4, 'Temporary', 'Day')
into job_type values(442, 'Part-time', 'Part-time role for students', 'Yes', 4, 'Temporary', 'Night')
into job_type values(443, 'Part-time', 'Part-time role for students', 'Yes', 4, 'Temporary', 'Rotating')
into job_type values(444, 'Part-time', 'Part-time role for students', 'Yes', 4, 'Temporary', 'Flexible')
into job_type values(445, 'Internship', 'Internship for gaining experience', 'Yes', 6, 'Internship', 'Day')
into job_type values(446, 'Internship', 'Internship for gaining experience', 'Yes', 6, 'Internship', 'Night')
into job_type values(447, 'Internship', 'Internship for gaining experience', 'Yes', 6, 'Internship', 'Rotating')
into job_type values(448, 'Internship', 'Internship for gaining experience', 'Yes', 6, 'Internship', 'Flexible')
into job_type values(449, 'Full-time', 'Full-time employment with benefits', 'No', 8, 'Permanent', 'Day')
into job_type values(450, 'Full-time', 'Full-time employment with benefits', 'No', 8, 'Permanent', 'Night')
into job_type values(451, 'Full-time', 'Full-time employment with benefits', 'No', 8, 'Permanent', 'Rotating')
into job_type values(452, 'Full-time', 'Full-time employment with benefits', 'No', 8, 'Permanent', 'Flexible')
into job_type values(453, 'Part-time', 'Part-time flexible job', 'Yes', 4, 'Temporary', 'Day')
into job_type values(454, 'Part-time', 'Part-time flexible job', 'Yes', 4, 'Temporary', 'Night')
into job_type values(455, 'Part-time', 'Part-time flexible job', 'Yes', 4, 'Temporary', 'Rotating')
into job_type values(456, 'Part-time', 'Part-time flexible job', 'Yes', 4, 'Temporary', 'Flexible')
into job_type values(457, 'Internship', 'Paid internship opportunity', 'Yes', 6, 'Internship', 'Day')
into job_type values(458, 'Internship', 'Paid internship opportunity', 'Yes', 6, 'Internship', 'Night')
into job_type values(459, 'Internship', 'Paid internship opportunity', 'Yes', 6, 'Internship', 'Rotating')
into job_type values(460, 'Internship', 'Paid internship opportunity', 'Yes', 6, 'Internship', 'Flexible')
into job_type values(461, 'Full-time', 'Full-time job with career growth', 'No', 8, 'Permanent', 'Day')
into job_type values(462, 'Full-time', 'Full-time job with career growth', 'No', 8, 'Permanent', 'Night')
into job_type values(463, 'Full-time', 'Full-time job with career growth', 'No', 8, 'Permanent', 'Rotating')
into job_type values(464, 'Full-time', 'Full-time job with career growth', 'No', 8, 'Permanent', 'Flexible')
into job_type values(465, 'Part-time', 'Part-time work with career development', 'Yes', 4, 'Temporary', 'Day')
into job_type values(466, 'Part-time', 'Part-time work with career development', 'Yes', 4, 'Temporary', 'Night')
into job_type values(467, 'Part-time', 'Part-time work with career development', 'Yes', 4, 'Temporary', 'Rotating')
into job_type values(468, 'Part-time', 'Part-time work with career development', 'Yes', 4, 'Temporary', 'Flexible')
into job_type values(469, 'Internship', 'Internship to gain practical skills', 'Yes', 6, 'Internship', 'Day')
into job_type values(470, 'Internship', 'Internship to gain practical skills', 'Yes', 6, 'Internship', 'Night')
select * from dual;


insert all
into companies values(501, 'TCS', 1968, 500000, 'www.tcs.com', 'info@tcs.com', 9123456001, 'Large', 'Mumbai, India')
into companies values(502, 'Infosys', 1981, 300000, 'www.infosys.com', 'info@infosys.com', 9123456002, 'Large', 'Bangalore, India')
into companies values(503, 'Mahindra', 1945, 200000, 'www.mahindra.com', 'info@mahindra.com', 9123456003, 'Large', 'Mumbai, India')
into companies values(504, 'Accenture', 1989, 700000, 'www.accenture.com', 'info@accenture.com', 9123456004, 'Large', 'Dublin, Ireland')
into companies values(505, 'Cognizant', 1994, 350000, 'www.cognizant.com', 'info@cognizant.com', 9123456005, 'Large', 'Teaneck, USA')
into companies values(506, 'Wipro', 1945, 200000, 'www.wipro.com', 'info@wipro.com', 9123456006, 'Large', 'Bangalore, India')
into companies values(507, 'HCL', 1976, 150000, 'www.hcl.com', 'info@hcl.com', 9123456007, 'Large', 'Noida, India')
into companies values(508, 'Amazon', 1994, 1600000, 'www.amazon.com', 'info@amazon.com', 9123456008, 'Large', 'Seattle, USA')
into companies values(509, 'Microsoft', 1975, 220000, 'www.microsoft.com', 'info@microsoft.com', 9123456009, 'Large', 'Redmond, USA')
into companies values(510, 'Google', 1998, 150000, 'www.google.com', 'info@google.com', 9123456010, 'Large', 'Mountain View, USA')
into companies values(511, 'Apple', 1976, 154000, 'www.apple.com', 'info@apple.com', 9123456011, 'Large', 'Cupertino, USA')
into companies values(512, 'Reliance Industries', 1973, 300000, 'www.ril.com', 'info@ril.com', 9123456012, 'Large', 'Mumbai, India')
into companies values(513, 'Tata Motors', 1945, 80000, 'www.tatamotors.com', 'info@tatamotors.com', 9123456013, 'Large', 'Mumbai, India')
into companies values(514, 'Ford', 1903, 186000, 'www.ford.com', 'info@ford.com', 9123456014, 'Large', 'Dearborn, USA')
into companies values(515, 'BMW', 1916, 120000, 'www.bmw.com', 'info@bmw.com', 9123456015, 'Large', 'Munich, Germany')
into companies values(516, 'Nestle', 1867, 273000, 'www.nestle.com', 'info@nestle.com', 9123456016, 'Large', 'Vevey, Switzerland')
into companies values(517, 'Unilever', 1929, 149000, 'www.unilever.com', 'info@unilever.com', 9123456017, 'Large', 'London, UK')
into companies values(518, 'Coca-Cola', 1892, 80000, 'www.coca-cola.com', 'info@coca-cola.com', 9123456018, 'Large', 'Atlanta, USA')
into companies values(519, 'PepsiCo', 1965, 291000, 'www.pepsico.com', 'info@pepsico.com', 9123456019, 'Large', 'Purchase, USA')
into companies values(520, 'Sony', 1946, 111000, 'www.sony.com', 'info@sony.com', 9123456020, 'Large', 'Tokyo, Japan')
into companies values(521, 'Samsung', 1938, 309000, 'www.samsung.com', 'info@samsung.com', 9123456021, 'Large', 'Seoul, South Korea')
into companies values(522, 'IBM', 1911, 350000, 'www.ibm.com', 'info@ibm.com', 9123456022, 'Large', 'Armonk, USA')
into companies values(523, 'Siemens', 1847, 293000, 'www.siemens.com', 'info@siemens.com', 9123456023, 'Large', 'Munich, Germany')
into companies values(524, 'Volkswagen', 1937, 668000, 'www.volkswagen.com', 'info@volkswagen.com', 9123456024, 'Large', 'Wolfsburg, Germany')
into companies values(525, 'Toyota', 1937, 366000, 'www.toyota.com', 'info@toyota.com', 9123456025, 'Large', 'Toyota City, Japan')
into companies values(526, 'Honda', 1948, 220000, 'www.honda.com', 'info@honda.com', 9123456026, 'Large', 'Tokyo, Japan')
into companies values(527, 'Tesla', 2003, 127000, 'www.tesla.com', 'info@tesla.com', 9123456027, 'Large', 'Palo Alto, USA')
into companies values(528, 'Nike', 1964, 79000, 'www.nike.com', 'info@nike.com', 9123456028, 'Large', 'Beaverton, USA')
into companies values(529, 'Adidas', 1949, 59000, 'www.adidas.com', 'info@adidas.com', 9123456029, 'Large', 'Herzogenaurach, Germany')
into companies values(530, 'Procter & Gamble', 1837, 101000, 'www.pg.com', 'info@pg.com', 9123456030, 'Large', 'Cincinnati, USA')
into companies values(531, 'Walmart', 1962, 2300000, 'www.walmart.com', 'info@walmart.com', 9123456031, 'Large', 'Bentonville, USA')
into companies values(532, 'General Electric', 1892, 174000, 'www.ge.com', 'info@ge.com', 9123456032, 'Large', 'Boston, USA')
into companies values(533, 'ExxonMobil', 1999, 64000, 'www.exxonmobil.com', 'info@exxonmobil.com', 9123456033, 'Large', 'Irving, USA')
into companies values(534, 'Chevron', 1879, 48000, 'www.chevron.com', 'info@chevron.com', 9123456034, 'Large', 'San Ramon, USA')
into companies values(535, 'BP', 1909, 70000, 'www.bp.com', 'info@bp.com', 9123456035, 'Large', 'London, UK')
into companies values(536, 'Shell', 1907, 87000, 'www.shell.com', 'info@shell.com', 9123456036, 'Large', 'The Hague, Netherlands')
into companies values(537, 'Oracle', 1977, 143000, 'www.oracle.com', 'info@oracle.com', 9123456037, 'Large', 'Austin, USA')
into companies values(538, 'SAP', 1972, 107000, 'www.sap.com', 'info@sap.com', 9123456038, 'Large', 'Walldorf, Germany')
into companies values(539, 'Netflix', 1997, 123000, 'www.netflix.com', 'info@netflix.com', 9123456039, 'Large', 'Los Gatos, USA')
into companies values(540, 'Facebook', 2004, 87000, 'www.facebook.com', 'info@facebook.com', 9123456040, 'Large', 'Menlo Park, USA')
into companies values(541, 'Uber', 2009, 29000, 'www.uber.com', 'info@uber.com', 9123456041, 'Large', 'San Francisco, USA')
into companies values(542, 'Lyft', 2012, 5000, 'www.lyft.com', 'info@lyft.com', 9123456042, 'Medium', 'San Francisco, USA')
into companies values(543, 'Zoom', 2011, 6900, 'www.zoom.us', 'info@zoom.us', 9123456043, 'Medium', 'San Jose, USA')
into companies values(544, 'Spotify', 2006, 8200, 'www.spotify.com', 'info@spotify.com', 9123456044, 'Medium', 'Stockholm, Sweden')
into companies values(545, 'Adobe', 1982, 29000, 'www.adobe.com', 'info@adobe.com', 9123456045, 'Large', 'San Jose, USA')
into companies values(546, 'Salesforce', 1999, 77000, 'www.salesforce.com', 'info@salesforce.com', 9123456046, 'Large', 'San Francisco, USA')
into companies values(547, 'Airbnb', 2008, 6000, 'www.airbnb.com', 'info@airbnb.com', 9123456047, 'Medium', 'San Francisco, USA')
into companies values(548, 'Zomato', 2008, 3000, 'www.zomato.com', 'info@zomato.com', 9123456048, 'Medium', 'Gurgaon, India')
into companies values(549, 'Swiggy', 2014, 5000, 'www.swiggy.com', 'info@swiggy.com', 9123456049, 'Medium', 'Bangalore, India')
into companies values(550, 'Paytm', 2010, 7000, 'www.paytm.com', 'info@paytm.com', 9123456050, 'Medium', 'Noida, India')
into companies values(551, 'Flipkart', 2007, 30000, 'www.flipkart.com', 'info@flipkart.com', 9123456051, 'Large', 'Bangalore, India')
into companies values(552, 'Snapdeal', 2010, 5000, 'www.snapdeal.com', 'info@snapdeal.com', 9123456052, 'Medium', 'New Delhi, India')
into companies values(553, 'MakeMyTrip', 2000, 4000, 'www.makemytrip.com', 'info@makemytrip.com', 9123456053, 'Medium', 'Gurgaon, India')
into companies values(554, 'Ola', 2010, 10000, 'www.olacabs.com', 'info@ola.com', 9123456054, 'Medium', 'Bangalore, India')
into companies values(555, 'BYJUS', 2011, 6000, 'www.byjus.com', 'info@byjus.com', 9123456055, 'Medium', 'Bangalore, India')
into companies values(556, 'PhonePe', 2015, 5000, 'www.phonepe.com', 'info@phonepe.com', 9123456056, 'Medium', 'Bangalore, India')
into companies values(557, 'Zoomcar', 2013, 1200, 'www.zoomcar.com', 'info@zoomcar.com', 9123456057, 'Medium', 'Bangalore, India')
into companies values(558, 'BigBasket', 2011, 7000, 'www.bigbasket.com', 'info@bigbasket.com', 9123456058, 'Medium', 'Bangalore, India')
into companies values(559, 'Nykaa', 2012, 2500, 'www.nykaa.com', 'info@nykaa.com', 9123456059, 'Medium', 'Mumbai, India')
into companies values(560, 'Dream11', 2008, 1000, 'www.dream11.com', 'info@dream11.com', 9123456060, 'Medium', 'Mumbai, India')
into companies values(561, 'Meesho', 2015, 2000, 'www.meesho.com', 'info@meesho.com', 9123456061, 'Medium', 'Bangalore, India')
into companies values(562, 'Cure.fit', 2016, 4000, 'www.curefit.com', 'info@curefit.com', 9123456062, 'Medium', 'Bangalore, India')
into companies values(563, 'Razorpay', 2014, 5000, 'www.razorpay.com', 'info@razorpay.com', 9123456063, 'Medium', 'Bangalore, India')
into companies values(564, 'Cred', 2018, 1500, 'www.cred.club', 'info@cred.club', 9123456064, 'Medium', 'Bangalore, India')
into companies values(565, 'Freshworks', 2010, 5000, 'www.freshworks.com', 'info@freshworks.com', 9123456065, 'Medium', 'Chennai, India')
into companies values(566, 'Delhivery', 2011, 50000, 'www.delhivery.com', 'info@delhivery.com', 9123456066, 'Large', 'Gurgaon, India')
into companies values(567, 'Urban Company', 2014, 2000, 'www.urbancompany.com', 'info@urbancompany.com', 9123456067, 'Medium', 'Gurgaon, India')
into companies values(568, 'PolicyBazaar', 2008, 4000, 'www.policybazaar.com', 'info@policybazaar.com', 9123456068, 'Medium', 'Gurgaon, India')
into companies values(569, 'Zerodha', 2010, 1200, 'www.zerodha.com', 'info@zerodha.com', 9123456069, 'Medium', 'Bangalore, India')
into companies values(570, 'Swiggy Instamart', 2020, 4000, 'www.instamart.com', 'info@instamart.com', 9123456070, 'Medium', 'Bangalore, India')
select * from dual;


insert all
into employers values(601, 2, 501, 'Large', 'TCS', 'Mumbai, India', 'www.tcs.com', 'IT')
into employers values(602, 4, 502, 'Large', 'Infosys', 'Bangalore, India', 'www.infosys.com', 'IT')
into employers values(603, 70, 503, 'Large', 'Mahindra', 'Mumbai, India', 'www.mahindra.com', 'Automotive')
into employers values(604, 6, 504, 'Large', 'Accenture', 'Dublin, Ireland', 'www.accenture.com', 'IT')
into employers values(605, 8, 505, 'Large', 'Cognizant', 'Teaneck, USA', 'www.cognizant.com', 'IT')
into employers values(606, 10, 506, 'Large', 'Wipro', 'Bangalore, India', 'www.wipro.com', 'IT')
into employers values(607, 56, 507, 'Large', 'HCL', 'Noida, India', 'www.hcl.com', 'IT')
into employers values(608, 12, 508, 'Large', 'Amazon', 'Seattle, USA', 'www.amazon.com', 'E-commerce')
into employers values(609, 14, 509, 'Large', 'Microsoft', 'Redmond, USA', 'www.microsoft.com', 'IT')
into employers values(610, 58, 510, 'Large', 'Google', 'Mountain View, USA', 'www.google.com', 'IT')
into employers values(611, 16, 511, 'Large', 'Apple', 'Cupertino, USA', 'www.apple.com', 'IT')
into employers values(612, 18, 512, 'Large', 'Reliance Industries', 'Mumbai, India', 'www.ril.com', 'Conglomerate')
into employers values(613, 20, 513, 'Large', 'Tata Motors', 'Mumbai, India', 'www.tatamotors.com', 'Automotive')
into employers values(614, 22, 514, 'Large', 'Ford', 'Dearborn, USA', 'www.ford.com', 'Automotive')
into employers values(615, 24, 510, 'Large', 'BMW', 'Munich, Germany', 'www.bmw.com', 'Automotive')
into employers values(616, 32, 516, 'Large', 'Nestle', 'Vevey, Switzerland', 'www.nestle.com', 'Food & Beverage')
into employers values(617, 30, 517, 'Large', 'Unilever', 'London, UK', 'www.unilever.com', 'Food & Beverage')
into employers values(618, 26, 518, 'Large', 'Coca-Cola', 'Atlanta, USA', 'www.coca-cola.com', 'Food & Beverage')
into employers values(619, 28, 519, 'Large', 'PepsiCo', 'Purchase, USA', 'www.pepsico.com', 'Food & Beverage')
into employers values(620, 30, 520, 'Large', 'Sony', 'Tokyo, Japan', 'www.sony.com', 'Electronics')
into employers values(621, 32, 521, 'Large', 'Samsung', 'Seoul, South Korea', 'www.samsung.com', 'Electronics')
into employers values(622, 22, 522, 'Large', 'IBM', 'Armonk, USA', 'www.ibm.com', 'IT')
into employers values(623, 34, 523, 'Large', 'Siemens', 'Munich, Germany', 'www.siemens.com', 'Engineering')
into employers values(624, 24, 510, 'Large', 'Volkswagen', 'Wolfsburg, Germany', 'www.volkswagen.com', 'Automotive')
into employers values(625, 36, 525, 'Large', 'Toyota', 'Toyota City, Japan', 'www.toyota.com', 'Automotive')
into employers values(626, 26, 526, 'Large', 'Honda', 'Tokyo, Japan', 'www.honda.com', 'Automotive')
into employers values(627, 38, 522, 'Large', 'Tesla', 'Palo Alto, USA', 'www.tesla.com', 'Automotive')
into employers values(628, 28, 528, 'Large', 'Nike', 'Beaverton, USA', 'www.nike.com', 'Footwear')
into employers values(629, 2, 529, 'Large', 'Adidas', 'Herzogenaurach, Germany', 'www.adidas.com', 'Footwear')
into employers values(630, 30, 530, 'Large', 'Procter & Gamble', 'Cincinnati, USA', 'www.pg.com', 'Consumer Goods')
into employers values(631, 44, 531, 'Large', 'Walmart', 'Bentonville, USA', 'www.walmart.com', 'Retail')
into employers values(632, 32, 532, 'Large', 'General Electric', 'Boston, USA', 'www.ge.com', 'Conglomerate')
into employers values(633, 66, 533, 'Large', 'ExxonMobil', 'Irving, USA', 'www.exxonmobil.com', 'Oil & Gas')
into employers values(634, 34, 534, 'Large', 'Chevron', 'San Ramon, USA', 'www.chevron.com', 'Oil & Gas')
into employers values(635, 40, 535, 'Large', 'BP', 'London, UK', 'www.bp.com', 'Oil & Gas') 
into employers values(636, 2, 536, 'Large', 'Shell', 'The Hague, Netherlands', 'www.shell.com', 'Oil & Gas')
into employers values(637, 12, 537, 'Large', 'Oracle', 'Austin, USA', 'www.oracle.com', 'IT')
into employers values(638, 38, 538, 'Large', 'SAP', 'Walldorf, Germany', 'www.sap.com', 'IT')
into employers values(639, 26, 549, 'Large', 'Netflix', 'Los Gatos, USA', 'www.netflix.com', 'Entertainment')
into employers values(640, 40, 520, 'Large', 'Facebook', 'Menlo Park, USA', 'www.facebook.com', 'Social Media')
into employers values(641, 12, 541, 'Medium', 'Uber', 'San Francisco, USA', 'www.uber.com', 'Transportation')
into employers values(642, 42, 542, 'Medium', 'Lyft', 'San Francisco, USA', 'www.lyft.com', 'Transportation')
into employers values(643, 44, 523, 'Medium', 'Zoom', 'San Jose, USA', 'www.zoom.us', 'Telecommunications')
into employers values(644, 46, 544, 'Medium', 'Spotify', 'Stockholm, Sweden', 'www.spotify.com', 'Entertainment')
into employers values(645, 30, 545, 'Large', 'Adobe', 'San Jose, USA', 'www.adobe.com', 'Software')
into employers values(646, 46, 546, 'Large', 'Salesforce', 'San Francisco, USA', 'www.salesforce.com', 'Software')
into employers values(647, 48, 547, 'Medium', 'Airbnb', 'San Francisco, USA', 'www.airbnb.com', 'Hospitality')
into employers values(648, 50, 548, 'Medium', 'Zomato', 'Gurgaon, India', 'www.zomato.com', 'Food Delivery')
into employers values(649, 14, 549, 'Medium', 'Swiggy', 'Bangalore, India', 'www.swiggy.com', 'Food Delivery')
into employers values(650, 50, 520, 'Medium', 'Paytm', 'Noida, India', 'www.paytm.com', 'Fintech')
into employers values(651, 8, 551, 'Medium', 'Flipkart', 'Bangalore, India', 'www.flipkart.com', 'E-commerce')
into employers values(652, 52, 502, 'Medium', 'Snapdeal', 'Gurgaon, India', 'www.snapdeal.com', 'E-commerce')
into employers values(653, 36, 533, 'Medium', 'Myntra', 'Bangalore, India', 'www.myntra.com', 'E-commerce')
into employers values(654, 54, 554, 'Medium', 'BookMyShow', 'Mumbai, India', 'www.bookmyshow.com', 'Entertainment')
into employers values(655, 50, 555, 'Medium', 'Ola', 'Bangalore, India', 'www.ola.com', 'Transportation')
into employers values(656, 56, 556, 'Medium', 'Patanjali', 'Haridwar, India', 'www.patanjali.com', 'Consumer Goods')
into employers values(657, 52, 557, 'Medium', 'HDFC Bank', 'Mumbai, India', 'www.hdfcbank.com', 'Banking')
into employers values(658, 58, 558, 'Medium', 'ICICI Bank', 'Mumbai, India', 'www.icicibank.com', 'Banking')
into employers values(659, 20, 559, 'Medium', 'Axis Bank', 'Mumbai, India', 'www.axisbank.com', 'Banking')
into employers values(660, 60, 560, 'Medium', 'Kotak Mahindra Bank', 'Mumbai, India', 'www.kotak.com', 'Banking')
into employers values(661, 32, 502, 'Medium', 'Yes Bank', 'Mumbai, India', 'www.yesbank.in', 'Banking')
into employers values(662, 22, 562, 'Medium', 'Bank of Baroda', 'Mumbai, India', 'www.bankofbaroda.in', 'Banking')
into employers values(663, 60, 563, 'Medium', 'SBI', 'Mumbai, India', 'www.sbi.co.in', 'Banking')
into employers values(664, 64, 544, 'Medium', 'PNB', 'Mumbai, India', 'www.pnbindia.in', 'Banking')
into employers values(665, 26, 505, 'Medium', 'Citi Bank', 'Mumbai, India', 'www.citibank.com', 'Banking')
into employers values(666, 66, 566, 'Medium', 'Deutsche Bank', 'Mumbai, India', 'www.deutschebank.com', 'Banking')
into employers values(667, 18, 520, 'Medium', 'Goldman Sachs', 'New York, USA', 'www.goldmansachs.com', 'Finance')
into employers values(668, 68, 568, 'Medium', 'Morgan Stanley', 'New York, USA', 'www.morganstanley.com', 'Finance')
into employers values(669, 20, 519, 'Medium', 'JP Morgan', 'New York, USA', 'www.jpmorgan.com', 'Finance')
into employers values(670, 70, 570, 'Medium', 'Barclays', 'London, UK', 'www.barclays.com', 'Finance')
Select * from dual;